---
- hosts: all
  become: true
  tasks:

  - name: Add Docker GPG Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker to APT repository
    apt_repository:
      repo: "deb https://download.docker.com/linux/ubuntu focal stable"
      state: present

  - name: Install Docker Pre-requisites
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
      state: latest

  - name: Install Docker
    package:
      name: docker-ce
      state: latest

  - name: Start Docker Service
    service:
      name: docker
      state: started
      enabled: yes
